spring.application.name=backend

# SQLite
spring.datasource.url=jdbc:sqlite:database/carmatrix.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# SQL Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open Session In View
spring.jpa.open-in-view=false